Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StatTracker.Data;
using StatTracker.Extensions;
using StatTracker.Models;
using StatTracker.Models.Enums;
using StatTracker.Models.ViewModels;
using StatTracker.Services;
using StatTracker.Services.Interfaces;

namespace StatTracker.Controllers
{
    [Authorize]
    public class CompaniesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IBTFileService _btFileService;
        private readonly IBTProjectService _projectService;
        private readonly IBTRolesService _rolesService;
        private readonly IBTCompanyService _companyService;
        private readonly UserManager<BTUser> _userManager;

        public CompaniesController(ApplicationDbContext context, IBTFileService btFileService, IBTProjectService projectService, IBTRolesService rolesService, IBTCompanyService companyService, UserManager<BTUser> userManager)
        {
            _context = context;
            _btFileService = btFileService;
            _projectService = projectService;
            _rolesService = rolesService;
            _companyService = companyService;
            _userManager = userManager;
        }

        // GET: Companies
        public async Task<IActionResult> Index()
        {
            int companyId = User.Identity!.GetCompanyId();

            Company? company = await _companyService.GetCompanyInfoAsync(companyId);

            return View(company);
                          
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Companies == null)
            {
                return NotFound();
            }

            var company = await _context.Companies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // GET: Companies/AddTicketComment
        public IActionResult Create()
        {
            return View();
        }

        // POST: Companies/AddTicketComment
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,ImageFileData,ImageFileType")] Company company)
        {
            if (ModelState.IsValid)
            {
                _context.Add(company);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        // GET: Companies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Companies == null)
            {
                return NotFound();
            }

            var company = await _context.Companies.FindAsync(id);
            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,ImageFileData,ImageFileType")] Company company)
        {
            if (id != company.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(company);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyExists(company.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Companies == null)
            {
                return NotFound();
            }

            var company = await _context.Companies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Companies == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Company'  is null.");
            }
            var company = await _context.Companies.FindAsync(id);
            if (company != null)
            {
                _context.Companies.Remove(company);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> ManageUserRoles()
        {
            List<ManageUserRolesViewModel> model = new();

            // Get companyId
            int companyId = User.Identity!.GetCompanyId();

            Company? company = await _companyService.GetCompanyByIdAsync(companyId);

            IEnumerable<BTUser> companyUsers = await _context.Users.Where(u => u.CompanyId == companyId).ToListAsync();

            List<IdentityRole> roles = await _rolesService.GetRolesAsync();

            foreach (BTUser user in companyUsers)
            {
                ManageUserRolesViewModel rolesViewModel = new()
                {
                    BTUser = user,
                    Roles = new MultiSelectList(roles, "Name", "Name", await _rolesService.GetUserRolesAsync(user))
                };

                model.Add(rolesViewModel);
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageUserRoles(ManageUserRolesViewModel viewModel)
        {
            // Get companyId
            int companyId = User.Identity!.GetCompanyId();

            BTUser? btUser = await _userManager.FindByIdAsync(viewModel.BTUser!.Id);

            if (btUser == null)
            {
                return NotFound();
            }

            IEnumerable<string> roles = await _rolesService.GetUserRolesAsync(btUser);

            IEnumerable<string> selectedRoles = viewModel.SelectedRoles;

            await _rolesService.RemoveUserFromRolesAsync(btUser, selectedRoles);

            foreach (string role in selectedRoles)
            {
                await _rolesService.AddUserToRoleAsync(btUser, role);
            }

            return RedirectToAction(nameof(Index));
        }


        private bool CompanyExists(int id)
        {
          return (_context.Companies?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;
using StatTracker.Data;
using StatTracker.Extensions;
using StatTracker.Models;
using StatTracker.Services.Interfaces;
using StatTracker.Models.ViewModels;
using StatTracker.Models.Enums;
using StatTracker.Services;
using X.PagedList;

namespace StatTracker.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<BTUser> _userManager;
        private readonly IBTFileService _btFileService;
        private readonly IBTProjectService _projectService;
        private readonly IBTRolesService _rolesService;
        private readonly IBTCompanyService _companyService;

        public ProjectsController(ApplicationDbContext context, UserManager<BTUser> userManager, IBTFileService btFileService, IBTProjectService projectService, IBTRolesService rolesService, IBTCompanyService companyService)
        {
            _context = context;
            _userManager = userManager;
            _btFileService = btFileService;
            _projectService = projectService;
            _rolesService = rolesService;
            _companyService = companyService;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AssignPM(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Get companyId
            int companyId = User.Identity!.GetCompanyId();

            IEnumerable<BTUser?> projectManagers = await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.ProjectManager), companyId);
            BTUser? currentPM = await _projectService.GetProjectManagerAsync(id);
            AssignPMViewModel viewModel = new()
            {
                Project = await _projectService.GetProjectByIdAsync(id, companyId),
                PMList = new SelectList(projectManagers, "Id", "FullName", currentPM?.Id),
                PMId = currentPM?.Id,
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AssignPM(AssignPMViewModel viewModel)
        {
            if (!string.IsNullOrEmpty(viewModel.PMId))
            {
                await _projectService.AddProjectManagerAsync(viewModel.PMId!, viewModel.Project!.Id);
                return RedirectToAction(nameof(Details), new { id = viewModel.Project?.Id });
            }

            ModelState.AddModelError("PMId", "No Project Manager chosen. Please select a PM.");

            // Get companyId
            int companyId = User.Identity!.GetCompanyId();

            IEnumerable<BTUser>? projectManagers = await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.ProjectManager), companyId);
            BTUser? currentPM = await _projectService.GetProjectManagerAsync(viewModel.Project?.Id);
            viewModel.Project = await _projectService.GetProjectByIdAsync(viewModel.Project?.Id, companyId);
            viewModel.PMList = new SelectList(projectManagers, "Id", "FullName", currentPM?.Id);
            viewModel.PMId = currentPM?.Id;

            return View(viewModel);

        }

        [HttpGet]
        [Authorize(Roles = "Admin, ProjectManager")]
        public async Task<IActionResult> AssignProjectMembers(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Get companyId
            int companyId = User.Identity!.GetCompanyId();

            Project? project = await _projectService.GetProjectByIdAsync(id, companyId);

            List<BTUser> submitters = await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.Submitter), companyId);
            List<BTUser> developers = await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.Developer), companyId);

            List<BTUser> userList = submitters.Concat(developers).ToList();

            List<string> currentMembers = project.Members.Select(m => m.Id).ToList();

            ProjectMembersViewModel viewModel = new()
            {
                Project = project,
                UserList = new MultiSelectList(userList, "Id", "FullName", currentMembers)
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, ProjectManager")]
        public async Task<IActionResult> AssignProjectMembers(ProjectMembersViewModel viewModel)
        {
            // Get companyId
            int companyId = User.Identity!.GetCompanyId();

            if (viewModel.SelectedMembers != null)
            {
                // Remove current members
                await _projectService.RemoveMembersFromProjectAsync(viewModel.Project!.Id, companyId);

                // Add newly selected members
                await _projectService.AddMembersToProjectAsync(viewModel.SelectedMembers, viewModel.Project!.Id, companyId);
                return RedirectToAction(nameof(Details), new { id = viewModel.Project?.Id });
            }

            ModelState.AddModelError("SelectedMembers", "No Users chosen. Please select Users.");

            // Reset the form
            viewModel.Project = await _projectService.GetProjectByIdAsync(viewModel.Project!.Id, companyId);

            List<BTUser?> submitters = await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.Submitter), companyId);
            List<BTUser?> developers = await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.Developer), companyId);

            List<BTUser?> userList = submitters.Concat(developers).ToList();

            List<string> currentMembers = viewModel.Project.Members.Select(m => m.Id).ToList();

            viewModel.UserList = new MultiSelectList(userList, "id", "FullName", currentMembers);

            return View(viewModel);
        }

        // GET: Projects
        public async Task<IActionResult> Index(int? pageNum)
        {
            int companyId = User.Identity!.GetCompanyId();
            int pageSize = 9;
            int page = pageNum ?? 1;

            IPagedList<Project> projects = (await _projectService.GetProjectsAsync(companyId)).ToPagedList(page, pageSize);

            return View(projects);
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            int companyId = User.Identity!.GetCompanyId();

            Project project = await _projectService.GetProjectAsync(id.Value, companyId);


            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Projects/
        public async Task<IActionResult> Create()
        {
            ViewData["CompanyId"] = new SelectList(await _companyService.GetCompaniesAsync(), "Id", "Name");
            ViewData["ProjectPriorityId"] = new SelectList(await _projectService.GetProjectPrioritiesAsync(), "Id", "Name");

            Project project = new Project();
            project.StartDate = DataUtility.GetPostGresDate(DateTime.UtcNow);
            project.EndDate = DataUtility.GetPostGresDate(DateTime.UtcNow);
            return View(project);
        }

        // POST: Projects/
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CompanyId,Name,Description,Created,StartDate,EndDate,ProjectPriorityId,ImageFormFile,Archived")] Project project)
        {
            //ModelState.Remove("CompanyId");

            if (ModelState.IsValid)
            {
                int companyId = User.Identity!.GetCompanyId();
                // display information based on company
                //project.CompanyId = _userManager.GetUserId(User);

                project.Created = DataUtility.GetPostGresDate(DateTime.Now);
                project.StartDate = DataUtility.GetPostGresDate(project.StartDate);
                project.EndDate = DataUtility.GetPostGresDate(project.EndDate);

                // image service
                if (project.ImageFormFile != null)
                {
                    project.ImageFileData = await _btFileService.ConvertFileToByteArrayAsync(project.ImageFormFile);
                    project.ImageFileType = project.ImageFormFile.ContentType;
                }

                project.CompanyId = companyId;

                await _projectService.AddProjectAsync(project);

                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(await _companyService.GetCompaniesAsync(), "Id", "Name", project.CompanyId);
            ViewData["ProjectPriorityId"] = new SelectList(await _projectService.GetProjectPrioritiesAsync(), "Id", "Name", project.ProjectPriorityId);
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Projects == null)
            {
                return NotFound();
            }

            var project = await _context.Projects.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            ViewData["CompanyId"] = new SelectList(await _companyService.GetCompaniesAsync(), "Id", "Name", project.CompanyId);

Views/Projects/AssignPM.cshtml
@model AssignPMViewModel

@using StatTracker.Models.ViewModels


@{
    ViewData["Title"] = "Assign Project Manager";
}
<div class="d-flex justify-content-center mt-5 flex-column align-items-center">
    <h3 class="my-5">Assign Project Manager</h3>
    <div class="card">
        <div class="card-header">
            <div class="card-title">@Model.Project?.Name</div>
        </div>
        <div class="card-body">
            <form asp-action="AssignPM" asp-controller="Projects" method="post" class="d-flex flex-column">
                <input type="hidden" asp-for="Project!.Id" />
                <select asp-items="Model.PMList" asp-for="PMId">
                    <option value="">Unassigned</option>
                </select>
                <span asp-validation-for="PMId" class="text-danger"></span>
                <button type="submit" class="btn btn-primary my-3">Save</button>
                <a asp-action="Details" asp-route-id="@Model.Project?.Id" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>

Views/Projects/AssignProjectMembers.cshtml
@model ProjectMembersViewModel

@using StatTracker.Models.ViewModels

@{
    ViewData["Title"] = "Assign Project Members";
}
<div class="d-flex justify-content-center mt-5 flex-column align-items-center">
    <h3 class="my-5">Assign Project Member</h3>
    <div class="card">
        <div class="card-header">
            <div class="card-title">@Model.Project?.Name</div>
        </div>
        <div class="card-body">
            <form asp-action="AssignProjectMembers" asp-controller="Projects" method="post" class="d-flex flex-column">
                <input type="hidden" asp-for="Project!.Id" />
                <select asp-items="Model.UserList" asp-for="SelectedMembers" class="form-control" multiple required>
                    <option value="">Select Members</option>
                </select>
                <span asp-validation-for="UserList" class="text-danger"></span>
                <button type="submit" class="btn btn-primary my-3">Save</button>
                <a asp-action="Details" asp-route-id="@Model.Project?.Id" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>

Views/Projects/Delete.cshtml
@model StatTracker.Models.Project

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.Raw(Model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company!.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPriority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectPriority!.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a asp-action="Index" class="btn btn-outline-secondary">Back to List</a>
    </form>
</div>

Views/Projects/Index.cshtml
@model IPagedList<StatTracker.Models.Project>

@using StatTracker.Services.Interfaces
@using StatTracker.Models.Enums
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;
@using StatTracker.Extensions;
@using Microsoft.AspNetCore.Identity;

@inject IBTFileService _btFileService
@inject UserManager<BTUser> _UserManager;
@inject IBTRolesService _btRoleService;
@inject IBTFileService _btFileService;
@inject IBTProjectService _btProjectService;

@{
    ViewData["Title"] = "Index";
    BTUser? btUser = await _UserManager.GetUserAsync(User);
}

@if (User.IsInRole(nameof(BTRoles.Admin)))
{
    <div class="row">
        <div class="col-sm-4">
            <a asp-controller="Projects" asp-action="Create" class="btn btn-purple rounded-pill w-md waves-effect waves-light mb-3"><i class="mdi mdi-plus"></i> Create Project</a>
            <a asp-controller="Invites" asp-action="Create" class="btn btn-purple rounded-pill w-md waves-effect waves-light mb-3"><i class="mdi mdi-plus"></i> Invite Member</a>
        </div>
    </div>
    <!-- end row -->
}


<div class="row rol-cols-3 g-3">
    @foreach (Project project in Model)
    {
        <div class="col-xl-4">
            <div class="card h-100">
                <div class="card-body project-box">
                    <div class="float-end">
                        @if (project.ProjectPriority?.Name == nameof(BTProjectPriorities.Urgent))
                        {
                            <span class="badge bg-danger font-13">@nameof(BTProjectPriorities.Urgent)</span>
                        }
                        else if (project.ProjectPriority?.Name == nameof(BTProjectPriorities.High))
                        {
                            <span class="badge bg-warning font-13">@nameof(BTProjectPriorities.High)</span>
                        }
                        else if (project.ProjectPriority?.Name == nameof(BTProjectPriorities.Medium))
                        {
                            <span class="badge bg-primary font-13">@nameof(BTProjectPriorities.Medium)</span>
                        }
                        else if (project.ProjectPriority?.Name == nameof(BTProjectPriorities.Low))
                        {
                            <span class="badge bg-success font-13">@nameof(BTProjectPriorities.Low)</span>
                        }
                    </div>
                    <h4 class="mt-0"><a asp-controller="Projects" asp-action="Details" asp-route-id="@project.Id" class="text-dark">@Html.DisplayFor(modelItem => project.Name)</a></h4>
                    @*<p class="text-muted font-13" style="overflow-y:auto;height:250px;">
                @Html.Raw(project.Description)
                </p>*@
                    <ul class="list-inline">
                        <li class="list-inline-item me-4">
                            <h5 class="mb-0">Start Date:</h5>
                            <p class="text-muted">@project.StartDate.ToString("MM/dd/yy hh tt")</p>
                        </li>
                        <li class="list-inline-item float-end text-end">
                            <h5 class="mb-0">End Date:</h5>
                            <p class="text-muted">@project.EndDate.ToString("MM/dd/yy hh tt")</p>
                        </li>
                    </ul>

                    <div class="project-members mb-2">
                        <h5 class="float-start me-3">Team :</h5>
                        <div class="avatar-group">
                            @foreach (BTUser user in project.Members)
                            {
                                <a href="#" class="avatar-group-item" data-bs-toggle="tooltip" data-bs-placement="top" title="@user.FullName">
                                    <img src="@_btFileService.ConvertByteArrayToFile(project.ImageFileData!, project.ImageFileType!, (int)DefaultImage.BTUserImage)" alt="Post Images" class="rounded-circle avatar-sm" />
                                </a>
                            }
                            @if (User.IsInRole(nameof(BTRoles.Admin)))
                            {
                                <a asp-action="AssignProjectMembers" asp-route-id="@project.Id" data-bs-toggle="tooltip" data-bs-placement="top" title="Assign a new member">
                                    <span class="add-new-plus"><i class="mdi mdi-plus"></i></span>
                                </a>
                            }
                        </div>
                    </div>

                    @*<h5>Progress <span class="text-success float-end">80%</span></h5>
                <div class="progress progress-bar-alt-success progress-sm">
                <div class="progress-bar bg-success progress-animated wow animated animated"
                role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"
                style="width: 80%; visibility: visible; animation-name: animationProgress;">
                </div><!-- /.progress-bar .progress-bar-danger -->
                </div><!-- /.progress .no-rounded -->*@
                    @* Razor code block *@
                    @{
                        var start = project.StartDate;
                        var end = project.EndDate;
                        var today = DateTime.Now;
                        var percent = today >= end ? 100 : today < start ? 0 : Math.Round((today.Subtract(start)) / (end.Subtract(start)) * 100);
                    }
                    <h5>Progress <span class="text-primary float-end">@percent %</span></h5>
                    <div class="progress progress-bar-alt-primary progress-sm">
                        <div class="progress-bar bg-primary progress-animated wow animated animated"
                             role="progressbar"
                             style="width: @percent%; visibility: visible; animation-name: animationProgress;">
                        </div>
                    </div>

                </div>
            </div>

        </div>

        <!-- end col-->
    }
</div>
<!-- end row -->

<div id="page-selector">
    <div>
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    </div>
    @Html.PagedListPager(Model, pageNum => Url.Action("Index", new { pageNum }),
    new PagedListRenderOptions {
    ContainerDivClasses = new string[] { "btn-group" },
    UlElementClasses = new string[] { "justify-content-center" },
    LiElementClasses = new string[] { "btn", "btn-purple", "fab", "fw-bold", "text-white", "me-2" },
    })
</div>

@section Scripts {
    <!-- Pagination -->
    <script>
        let a = document.createElement('a');
        let span = document.querySelector('#page-selector span');
        a.textContent = span.textContent;
        a.style.background = '#3858f6';
        a.style.color = "#ffffff";
        span.replaceWith(a);
    </script>
}

Views/Projects/ManageUserRoles.cshtml
@model ManageUserRolesViewModel



@{
    ViewData["Title"] = "Assign Project Members";
}

<div class="row">
    <h2 class="m-t-0 h3"><b>Manage Member Roles </b></h2>
    @foreach (var viewModel in Model)
    {
        <div class="row">
            <div class="card col-4 m-3">
                <div class="card-body">
                    <p class="text-muted font-13 m-b-30">
                        This form displays the current roles assigned to the user: <strong class="text-info">@viewModel.BTUser!.FullName</strong>.
                        Use the dropdown to select the roles this user should be assigned.
                        Once roles are selected, click "Assign Roles" to submit the form.
                    </p>
                    <hr />
                    <form asp-action="ManageUserRoles" asp-controller="Companies" method=post>
                        <input type="hidden" asp-for="@viewModel.BTUser.Id" />
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="@viewModel.Roles" class="custom-label"> Roles for @viewModel.BTUser.FullName </label>
                                    <select asp-for="@viewModel.SelectedRoles" class="form-control" asp-items="@viewModel.Roles">
                                    </select>
                                    <hr />
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Assign Role" class="btn btn-info" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    }
</div>